/**
 * Per-account branding — the shared vocabulary.
 *
 * A branded account replaces two things: the mark + name at the top of
 * the sidebar, and the browser tab (title + favicon). Those live in
 * completely different places — a client component and a server
 * `generateMetadata` — so the fallback rule has to live in exactly one
 * place or the two surfaces drift apart and a customer sees their logo
 * in the app while the tab still says "wacrm".
 *
 * Everything here is pure: no Supabase import, no `window`. That is
 * what lets both a React client component and a server layout use it.
 */

/** Storage bucket created by migration 043. */
export const BRAND_BUCKET = "brand-assets";

/** Mirrors `accounts_brand_name_len` (migration 043). */
export const MAX_BRAND_NAME_LEN = 60;

/** Mirrors the bucket's `file_size_limit` (1 MB, migration 043). */
export const MAX_LOGO_BYTES = 1024 * 1024;

/**
 * Mirrors the bucket's `allowed_mime_types`. Kept identical on
 * purpose: if the browser-side list were wider, the picker would
 * accept a file that Storage then rejects with an opaque error after
 * the upload has already started. SVG is excluded deliberately — see
 * the migration for why a public bucket must not serve it.
 */
export const LOGO_MIME = ["image/png", "image/jpeg", "image/webp"] as const;

/** The `accept` attribute for the file input, derived so it cannot drift. */
export const LOGO_ACCEPT = LOGO_MIME.join(",");

/**
 * Product name used when an account has not configured branding.
 * Matches the root layout's title so an unbranded account is
 * indistinguishable from how the app behaved before branding existed.
 */
export const DEFAULT_BRAND_TITLE = "wacrm";

/** The branding columns as stored on `accounts`. */
export interface BrandRow {
  brand_name?: string | null;
  logo_url?: string | null;
}

/** What every surface actually renders. */
export interface Brand {
  /** Display name. Never empty — falls back to the generic product name. */
  title: string;
  /** Public URL of the uploaded logo, or null to render the default mark. */
  logoUrl: string | null;
  /** True when this account configured its own name (not the fallback). */
  isCustom: boolean;
}

/**
 * Trim a user-entered brand name into what the database will accept.
 *
 * Returns `null` for empty / whitespace-only input rather than `""`:
 * the `accounts_brand_name_len` CHECK rejects the empty string, and
 * more importantly "no branding" must have exactly one representation
 * in the column or every read site needs to test for two.
 */
export function normalizeBrandName(raw: string | null | undefined): string | null {
  if (typeof raw !== "string") return null;
  const trimmed = raw.trim();
  if (trimmed.length === 0) return null;
  return trimmed.slice(0, MAX_BRAND_NAME_LEN);
}

/**
 * Resolve a stored row into what the UI renders.
 *
 * `fallbackTitle` is passed in rather than defaulted here because the
 * client has a translated string available (`Sidebar.title`) while the
 * server does not — the server uses `DEFAULT_BRAND_TITLE`.
 */
export function resolveBrand(
  row: BrandRow | null | undefined,
  fallbackTitle: string = DEFAULT_BRAND_TITLE,
): Brand {
  const name = normalizeBrandName(row?.brand_name);
  const logo = typeof row?.logo_url === "string" && row.logo_url.length > 0
    ? row.logo_url
    : null;
  return {
    title: name ?? fallbackTitle,
    logoUrl: logo,
    isCustom: name !== null,
  };
}

/**
 * Recover the Storage object path from a public URL, so a replaced or
 * removed logo can be deleted from the bucket.
 *
 * Storing the path in a third column would be the other option, but it
 * is a second piece of state that can fall out of sync with
 * `logo_url`; the public URL shape is generated by supabase-js's
 * `getPublicUrl` and is stable, so deriving is safer than duplicating.
 *
 * Returns `null` for anything that is not a public URL of this bucket
 * — a logo set by hand in SQL, or one pointing at another host. The
 * caller then simply skips the delete instead of guessing at a path.
 */
export function parseBrandAssetPath(
  publicUrl: string | null | undefined,
): string | null {
  if (typeof publicUrl !== "string") return null;
  const marker = `/object/public/${BRAND_BUCKET}/`;
  const at = publicUrl.indexOf(marker);
  if (at === -1) return null;
  // Drop any query string (supabase-js can append a cache-buster) and
  // decode, because the stored URL is percent-encoded while the
  // Storage API expects the raw object path.
  const raw = publicUrl.slice(at + marker.length).split(/[?#]/)[0];
  if (raw.length === 0) return null;
  try {
    return decodeURIComponent(raw);
  } catch {
    // Malformed percent-encoding — better to skip the delete than to
    // throw inside a best-effort cleanup path.
    return null;
  }
}

/**
 * Build the `title` / `icons` half of the dashboard's metadata.
 *
 * `title.absolute` and NOT `title.default`, and this is load-bearing:
 * Next resolves `default` through the parent segment's template
 * (`resolveTitleTemplate(stashedTemplate, title.default)` in
 * next/dist/lib/metadata/resolvers/resolve-title.js), so with the root
 * layout's `template: "%s — wacrm"` a branded account would read
 * "Acme — wacrm" in the tab. `absolute` bypasses the parent template.
 * There is a test pinning this.
 */
export function buildBrandMetadata(brand: Brand): {
  title: { absolute: string; template: string };
  icons: { icon: { url: string }[] };
} {
  return {
    title: {
      absolute: brand.title,
      // Keep a template so a future page-level title renders as
      // "Page — Acme" rather than losing the brand entirely.
      template: `%s — ${brand.title}`,
    },
    // `/icon` is the build-time generated default mark (src/app/icon.tsx).
    icons: { icon: [{ url: brand.logoUrl ?? "/icon" }] },
  };
}
